services:
  - type: web
    name: glamping-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: glampingdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
