# Generated by Django 5.2.4 on 2025-08-15 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlampProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='glamp_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
                'indexes': [models.Index(fields=['status'], name='glamp_proje_status_26e1cf_idx'), models.Index(fields=['name'], name='glamp_proje_name_7662a1_idx')],
            },
        ),
    ]
