# Generated by Django 5.2.4 on 2025-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image_landscape',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image_portrait',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/'),
        ),
    ]
