# Generated by Django 5.2.4 on 2025-08-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_accommodation_image_landscape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
